// Generated by Rec Studio 4 - build Sep 23 2015 : Mason_Motschke - CSCI_370

_init()
{// addr = 0x00401000
    asm("invalid");
    __r9 = __r9 - 8;
    __rax = __imp____gmon_start__;
    if(__rax != 0) {
         *__rax();
    }
    __r9 = __r9 + 8;
}

_start(
    _unknown_ __rax,                       // r53
    _unknown_ __rdx                        // r56
)
{// addr = 0x00401040
    __rax = __rax;
    asm("invalid");
    _pop(__rsi);
    __r9 = __r9 & -16;
    _push(__rax);
    _push(__r9);
    __imp____libc_start_main();
    asm("hlt");
    asm("invalid");
}

_dl_relocate_static_pie(
    _unknown_ __rax                        // r53
)
{// addr = 0x00401070
    __rax = __rax;
    asm("invalid");
}

deregister_tm_clones(
    _unknown_ __rax                        // r53
)
{// addr = 0x00401080
    if(4210760 == 4210760 || 0 == 0) {
        return;
    } else {
        goto __rax;
    }
}

register_tm_clones(
    _unknown_ __rsi                        // r58
)
{// addr = 0x004010B0
    if((0 >> 63) + (0 >> 3) == 0 || 0 == 0) {
        return;
    } else {
        goto __rax;
    }
}

__do_global_dtors_aux(
    _unknown_ __rax                        // r53
)
{// addr = 0x004010F0
    _unknown_ _t1;                         // _t1

    __rax = __rax;
    asm("invalid");
    if(completed.8060 != 0) {
        return;
    } else {
        _push(_t1);
        deregister_tm_clones(__rax);
        completed.8060 = 1;
        _pop(__r8);
        return;
    }
}

frame_dummy(
    _unknown_ __rsi                        // r58
)
{// addr = 0x00401120
    asm("invalid");
    if((0 >> 63) + (0 >> 3) != 0 && 0 != 0) {
        goto __rax;
    }
}

__libc_csu_init(
    _unknown_ __rdx,                       // r56
    _unknown_ __rdi,                       // r57
    _unknown_ __rsi,                       // r58
    _unknown_ __r12                        // r63
)
{// addr = 0x00401160
    _unknown_ __rbx;                       // r54
    _unknown_ __r14;                       // r65
    _unknown_ __r15;                       // r66
    _unknown_ __rbp;                       // r67
    _unknown_ __rsp;                       // r68
    _unknown_ _t3;                         // _t3
    _unknown_ _t8;                         // _t8
    signed long long _t9;                  // _t9
    _unknown_ _t14;                        // _t14
    signed long long _t17;                 // _t17
    _unknown_ _t20;                        // _t20
    _unknown_ _t22;                        // _t22
    _unknown_ _t24;                        // _t24

    __rdi = __rdi;
    asm("invalid");
    _push(_t24);
    _push(_t22);
    _push(_t20);
    _push(__r14);
    _push(_t14);
    _push(_t8);
    __r9 = __r9 - 8;
    _init();
    _t17 =  &__do_global_dtors_aux_fini_array_entry -  &__frame_dummy_init_array_entry >> 3;
    if( &__do_global_dtors_aux_fini_array_entry != 0) {
        _t9 = 0;
        do {
             *((intOrPtr*)( &__frame_dummy_init_array_entry + _t9 * 8))();
            _t9 = _t9 + 1;
        } while(_t17 != _t9);
    }
    __r9 = __r9 + 8;
    _pop(__rbx);
    _pop(__r8);
    _pop(__r14);
    _pop(__r15);
    _pop(__rbp);
    _pop(__rsp);
}

__libc_csu_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x004011D0
    __rax = __rax;
    asm("invalid");
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x004011D8
    __rax = __rax;
    asm("invalid");
    __r9 = __r9 - 8;
    __r9 = __r9 + 8;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x004011D8
    __rax = __rax;
    asm("invalid");
    __r9 = __r9 - 8;
    __r9 = __r9 + 8;
}

// Statistics:
//      44 Register nodes
//      13 Temporaries nodes
//       1 Casts
//      48 Statements
//       0 Labels
//       0 Gotos
//      10 Blocks
//     203 Nodes
//      10 Assembly nodes
//      25 Unknown Types


Total time: 0 seconds.
